#!/bin/bash

alias srcit='source $HOME/.bashrc'
alias edbash='$EDITOR $HOME/.bash_profile'
alias edalias='$EDITOR $HOME/dotfiles/shell/aliases'
alias edtmux='$EDITOR ~/.tmux.conf'
function sk {
  tmux send-keys -t bottom-right $@ Enter
}
alias edvimrc='$EDITOR ~/.vimrc'
alias eddotfiles='(cd ~/dotfiles && v)'

# Remove executable
alias noexec='chmod -R -x+X'

# MacOS / Debian
if [[ $(uname) == Darwin ]]; then
  alias ipl='ifconfig en0 | grep inet | grep -v inet6 | awk "{print \$2}"'
  alias shutit='osascript -e "tell app \"System Events\" to shut down"'
  alias restartit='osascript -e "tell app \"System Events\" to restart"'
  alias sleepit='osascript -e "tell app \"System Events\" to sleep"'
  alias displayoff='pmset displaysleepnow'
  alias imout='(sleep 30 && shutit &) && tmux detach-client'
elif [[ $(uname -v) == *Debian* ]]; then
  alias ipl="xa@daileon:~$ ip addr | grep inet | grep -v inet6 | grep -v 127.0.0.1 |  awk "{print \$2}" | grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}'"
fi

# apps
alias firefox-dev='(/Applications/Firefox\ Developer\ Edition.app/Contents/MacOs/firefox &)'

# tests GUI for available colors, italics, etc
guitest() {
  for ((i = 0; i <= 79; i++)); do
    b=$(($i*255/79))
    g=$((2*$b))
    r=$((255-$b))
    if [[ $g -gt 255  ]]; then
      g=$((2*255 - $g))
    fi
    printf '\e[48;2;%d;%d;%dm \e[0m' $r $g $b
  done
  printf '\n'
  echo `tput sitm`italics`tput ritm` `tput smso`highlight`tput rmso` `tput smul`underline`tput rmul` `tput bold`bold`tput sgr0`
}

# cat
if [ "command -v pygmentize" != "" ]; then
  alias c='pygmentize -O style=monokai -f console256 -g'
fi

# ls
colorflag="--color"
export LSCOLORS='di=5;1:fi=0:ln=31:pi=5:so=5:bd=5:cd=5:or=31:mi=0:ex=35:*.rpm=90'
#GxFxCxDxBxegedabagGcGb
# di = directory
# fi = file
# ln = symlinks
# pi = fifo file (?)
# so = socket file
# bd = block (buffered)
# cd = character (unbuffered)
# or = orphan symlink (points to inexistent file)
# mi = non-existent file pointed to by a symlink
# ex = file which is executable (chmod -x)
alias ls="ls -a ${colorflag}" #ls plus colors and dotfiles
alias l="ls -lF ${colorflag}" # all files, in long format
alias la="ls -laF ${colorflag}" # all files inc dotfiles, in long format
alias lsd='ls -lF ${colorflag} | grep "^d"' # only directories

# tree
if [ "command -v tree" != "" ]; then
  #ignores .gitignore file extensions
  alias tree='tree -a -I $(cat ~/dotfiles/.gitignore | grep -v "^#.*$|^[[:space:]]*$" | tr "\\n" "|" | sed "s/.$//")'
fi

# vim/nvim
if [[ $EDITOR == 'nvim' ]]; then
  alias v='/usr/local/bin/nvim'
else
  alias v='/usr/local/bin/vim'
fi

# mkdir
alias mkdir='mkdir -p' #forces mkdir to create intermediate directories if a path is specified

# git
alias git='LANG=en_US git'
alias glog='git log --oneline --graph'

# tmux
alias mux=tmuxinator

# docker
alias dockill="docker rm -f \$(docker ps -aq)"
alias dockup='docker-compose up -d'
alias dcomp='docker-compose'
alias dockip="docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'"
alias dockimgclean="docker rmi -f \$(docker images -f dangling=true -q)"

# postgresql
alias fixpostgres="rm -f /usr/local/var/postgres/postmaster.pid && pg_ctl restart"
alias postgresps="lsof -n -i4TCP:5432"
alias sqlproxy="mkdir -p /tmp/cloudsql && ~/cloud_sql_proxy -dir=/tmp/cloudsql"

# kubernetes
alias k8="kubectl"

# npm
alias ng='npm list -g --depth=0 2>/dev/null' # lists packages globally, only the first level and throw stderr to the black hole
alias nl='npm list --depth=0 2>/dev/null' # same, but locally

alias youtube-dl='youtube-dl -o "~/Movies/youtube-dl/%(title)s.%(ext)s"'

# boilerplate
alias bpyarn="yarn add -D eslint babel-eslint eslint-config-prettier eslint-plugin-prettier jest prettier"
alias bpeslint="ln -s $HOME/dotfiles/rc/.eslintrc.json ."
alias bpjs='bpyarn; bpeslint'

# ffmpeg
function ffmpeg_convert_to_vp9webm {
  ffmpeg -i $1 -c:v libvpx-vp9 -b:v 2M output.webm
}
alias towebm=ffmpeg_convert_to_vp9webm

alias towebm8="ffmpeg -c:v libvpx -b:v 1M -c:a libvorbis outpute.webm -i "
