#!/bin/bash  ╱  ╱  ╱ ╱ ╱
# ╱ ╱ ╱ ╱  A   ╱ ╱ ╱ ╱ ╱
# ╱┳┳╮╭╮┳╮╱╭╮┳╭╮╱ ╱ ╱
# ╱┃┃┃┣┫┣┻╮┃╱┃┃┃╱ ╱ ╱ ╱ ╱
# ╱┛┛┛┻┗┻╱┗╰╯┻╰╯╱ ╱ ╱
# ╱┳┳╭┛┳┓┳┳╮╭╮┏┳┓╭╮┳╭┛
# ╱┃┣┻╮┣╱┃┃┃┣┫╱┃╱╰╮┃┃
# ╱┻┗╱┗┗┛┛┛┛┛┗╱┻╱╰╯╰┻
# ╱ ╱ ╱ ╱ ╱ ╱ ╱ DOTFILE ♡ ╱
# ╱ ╱ ╱ ╱ ╱ ╱ ╱  ╱ ╱ ╱
# ╱ ╱ ╱ ╱ ╱ ╱ ╱
# ╱ ╱ ╱ ╱ ╱ ╱ ╱
# ╱ ╱ ╱ ╱ ╱
# ╱ ╱ ╱                      marcio.ikematsu@usp.br
# ╱

set -o emacs

export LC_ALL=en_US.UTF-8
# export TERM=screen-256color
export TERM=xterm-256color
export CLICOLOR=1
export EDITOR=nvim
export MYVIMRC="~/.vimrc"

source $HOME/.bash_prompt
source $HOME/dotfiles/tmux/tmuxinator.bash
source $HOME/dotfiles/bash/settings.sh
source $HOME/dotfiles/bash/aliases.sh

  # Haskell
  # export PATH=$PATH:$HOME/.ghcup/bin
  export PATH=$PATH:$HOME/.cabal/bin

  # k8s
  # Krew
  # export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
# . /usr/local/opt/asdf/asdf.sh

# . /usr/local/opt/asdf/etc/bash_completion.d/asdf.bash

# vertical bar cursor
#echo -e -n "\x1b[\x35 q"

